name: Backend Check

on:
  push:
    branches:
      - 'main'
    paths:
      - 'dist/**.py'
      - 'src/**.py'
      - 'tests/**.py'
      - 'requirements/**.in'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'dist/**.py'
      - 'src/**.py'
      - 'tests/**.py'
      - 'requirements/**.in'

jobs:
  tox_checks:
    name: Run tox checks
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install tox and run
      run: |
          pip install --upgrade tox
          tox run-parallel
