name: Publish package to PyPI

on:
  release:
    types: [published]

jobs:

  publish-to-test-pypi:
    name: "Publish to Test PyPI"
    needs: [ "build", "provenance" ]
    permissions:
      id-token: write # Needed for trusted publishing to PyPI.
    runs-on: "ubuntu-latest"
    environment:
      name: "testpypi"
      url: "https://test.pypi.org/p/ngohub/${{ github.ref_name }}/"

    steps:
      - name: "Download dists"
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: "dist"
          path: "dist/"

      - name: "Publish dists to Test PyPI"
        uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0 # v1.9.0
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: "Publish to PyPI"
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ "publish-to-test-pypi" ]
    permissions:
      contents: write # Needed for making GitHub releases
      id-token: write # Needed for trusted publishing to PyPI.
    runs-on: "ubuntu-latest"
    environment:
      name: "publish"
      url: "https://pypi.org/p/ngohub/${{ github.ref_name }}/"

    steps:
      - name: "Download dists from release"
        run: |
          gh release download
          "${{ github.ref_name }}"
          --dir dist/
#          --pattern '*.tar.gz'
#          --pattern '*.whl'
#          --pattern '*.intoto.jsonl'
#          --pattern 'artifact/*'

      - name: "Publish dists to PyPI"
        uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0 # v1.9.0
